### ISSUE TITLE
Does it work with frameworks like Vue, Angular or React?

### ISSUE THREAD

**Issue by albertodeago** [leeoniya/dropcss#15]
see title!

By the way amazing library and thanks for sharing

**Comment by leeoniya** [comment]
hey @albertodeago 

it should work fine with anything that outputs html and css. you won't be able to feed .jsx or .vue files directly but once they're rendered to html (by the browser or renderToString), you can process that.

**Comment by albertodeago** [comment]
Great, I should have thought about that myself,
I will definetely try this out with Vue.

Thanks again

**Comment by leeoniya** [comment]
you may also find this useful: https://github.com/tailwindcss/docs/issues/161#issuecomment-482620671

**Comment by albertodeago** [comment]
Thanks for linking! I'll try it out
