### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by heygrady** [leeoniya/dropcss#16]
Don't want to paste in everything here but I ran into an issue where certain pages on my site would go into an infinite loop during the `dropcss` call. It's probably some weird css causing the issue but it's impossible to know because it gets stuck in the loop and never errors out.

**Comment by leeoniya** [comment]
sounds like either the html or css parser. it would be great to narrow down the specific part that does this. i would try chopping away all the html and see if it still hangs, then it's the css. and vice versa. the start chopping 50% of the problem htnl or css in a way that keeps it well-formed. you should eventually find where this happens and report it here.

you might get faster feedback by running your html and css through linters or validators and see if they find any parsing issues.

ultimately i want to bail out of the tokenizing loops if a single iteration does not advance any further and spit out the position and some before/after context of where it got stuck. i'm currently on vacation, but will try to get this implemented in the next 2 weeks (maybe a devmode build?)

**Comment by leeoniya** [comment]
> Don't want to paste in everything here

you can attach "everything" here in a zip if it's not sensitive and i can look at it, too.

**Comment by heygrady** [comment]
Here's an example:
https://repl.it/@heygrady/dropcss-example

**Comment by leeoniya** [comment]
should be fixed now. it was the lowly `<br/>`. the html parser was expecting whitespace to exist between the tagname and the trailing `>`.

**Comment by heygrady** [comment]
Is it still possible than an infinite loop will creep in? I can't use this in production if it enters infinite loops instead of erroring.

**Comment by leeoniya** [comment]
for now, yes.

though with every additional set of unique html/css processed the probability drops significantly. the checks in the loops should be rather simple to add, and you're welcome to contribute them sooner if you want to use this, best-in-class (imo) free-to-you lib "in production". otherwise you'll have to wait till i get around to it. it's not a priority for my personal use cases, since my code doesnt currently encounter these situations.

**Comment by leeoniya** [comment]
btw, sorry for putting it so bluntly, but there's a lot of entitlement that goes around open source.

for upaid open source projects, my primary interest is supporting my own use cases and no one else's suitability for "production" use. if it works for you, great, and you're welcome. if it doesn't, then please open a discussion or PR to support your use case or make your own private modifications to this MIT-licensed lib.

also, thanks for opening this issue - it's great to have additional test cases to find and fix bugs.

cheers!
