### ISSUE TITLE
Another infinite loop

### ISSUE THREAD

**Issue by heygrady** [leeoniya/dropcss#19]
Related #16

Here's an example:
https://repl.it/@heygrady/dropcss-example

It would be nice if it would throw instead of infinite looping. It doesn't matter much to me if this throws but infinite loops are a pretty big deal. Is it possible to put some runaway loop protection in place?

Regarding https://github.com/leeoniya/dropcss/issues/16#issuecomment-484268826

https://github.com/leeoniya/dropcss/blob/master/src/html.js#L66-L67
https://github.com/leeoniya/dropcss/blob/master/src/css.js#L159-L160

Would this basically fix it?
```js
let prevPos = pos
while (pos < html.length) {
	next();
	// is the problem that we stop advancing in some cases?
	if (prevPos === pos) {
		throw new Error('tokenizer did not advance');
		break;
	}
	prevPos = pos;
}
```

**Comment by leeoniya** [comment]
yeah that's the general idea. it would be useful to add some context to the error like pos, previous token (or prev x chars) and next x chars.

you can try temporarily undoing the `<br/>` fix with these guards in place and see if it makes the problem diagnosis trivial, too.

**Comment by heygrady** [comment]
BTW, the repl.it link is the same but the html/css it's testing has changed. I think that wasn't clear.

Anyway, not sure _why_ but the issue is that `find` is looping forever.

https://github.com/leeoniya/dropcss/blob/master/src/find.js#L186-L187

```js
			// if you count down the idx by default it will finish
			default:
				ctx.idx--;
```

`m` looks like this:
```json
"["body","_"," ","input","_",["'color'","=","type","["],["'date'","=","type","["],"not",":",["'week'","=","type","["],"not",":",["'range'","=","type","["],"not",":",["'radio'","=","type","["],"not",":",["'month'","=","type","["],"not",":",["'checkbox'","=","type","["],"not",":","not",":"]"
``

**Comment by leeoniya** [comment]
reduced initial testcase for this to:

```html
<body><input></body>
```

```css
body input:not([type='color']):not([type='checkbox']) {}
```
`:not` at least 2 times on a descendant element appears to be the necessary pre-condition to trigger this.

**Comment by leeoniya** [comment]
yeah, so this was a bug in the selector tokenizer. it was splicing the pseudos into the wrong position. that `m` you posted above definitely looked wrong. the specific fix was [line 39](https://github.com/leeoniya/dropcss/commit/111131265572eea74cfd4d7768b77501ff285887#diff-e3cedec16944707f68d276622a5549f0R39). that commit also includes a tweak to the attr regex to ignore surrounding single quotes around values (for normalization); before, only double quotes were ignored.

thanks!
