### ISSUE TITLE
alternative libs to test

### ISSUE THREAD

**Issue by denji** [leeoniya/dropcss#2]
https://github.com/peterbe/minimalcss

**Comment by leeoniya** [comment]
thanks for the link. i'm surprised this one evaded my radar given how mature it is.

here are some preliminary results:

lib size w/deps:
336 MB, 2,283 Files, 217 Folders

output size:
5.00 KB

there's no clear way to whitelist any rules to match up the results with the other libs, but it seems to clean well (as expected).

time elapsed:
1900ms

so, it's a mixed bag for sure.

while the results are good, it's a heavy solution that's ~15x slower than the current DropCSS, and maybe 25x slower by the time more optimizations are done to the selector engine. i have a hunch UnCSS can be fixed to get a bit better at cleaning and it'll still do it 4.5x faster (or more) than minimalcss and in pure JS to boot, at 24.5x smaller footprint.

**Comment by leeoniya** [comment]
https://github.com/oyvindeh/ucss
https://github.com/geuis/helium-css

**Comment by leeoniya** [comment]
i've finished a rewrite of DropCSS and it now completely obliterates ever other modern/maintained lib in performance, thoroughness and lib size. i'm confident there's nothing that approaches it at this time.
