### ISSUE TITLE
duplicated rules with same content

### ISSUE THREAD

**Issue by asfixia** [leeoniya/dropcss#24]
Hi why does this tool doesn't merge these two rules?

> <CSS>
> 
> 
> .x-btn-group-tl,.x-btn-group-tr{background-image: url(../ext/default/button/group-cs.gif);}
> .x-btn-group-bl,.x-btn-group-br{background-image: url(../ext/default/button/group-cs.gif);}
> 

> <Js>
> 
> const dropcss = require('dropcss');
> 
> var html = "";
> 
> var css = ".x-btn-group-tl,.x-btn-group-tr{background-image: url(../ext/default/button/group-cs.gif);}.x-btn-group-bl,.x-btn-group-br{background-image: url(../ext/default/button/group-cs.gif);}"
> 
> let cleaned = dropcss({
>     html,
>     css,
>     shouldDrop: (sel) => {
> 		return false;
>     },
> });
> 
> console.log(cleaned.css);

**Comment by leeoniya** [comment]
DropCSS does one thing: it removes unused CSS.

what you're looking for is a structural optimizer. there are several libs mentioned in the intro that perform this task: https://github.com/leeoniya/dropcss#introduction
