### ISSUE TITLE
Try DropCSS

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/dropcss#30]
Instead of spamming other libs' issues inviting people to try DropCSS, I'll just cc them here.

### Try DropCSS live: https://codepen.io/leeoniya/pen/LvbRyq

**Comment by leeoniya** [comment]
cc @mdickopp (via https://github.com/FullHuman/purgecss/issues/195)

**Comment by zavr-1** [comment]
@leeoniya bro this is superb library!!! thanks so much.

**Comment by leeoniya** [comment]
@zavr-1 glad you like it :P

**Comment by leeoniya** [comment]
cc @andybelldesign could be a good fit for [hylia](https://github.com/andybelldesign/hylia)

**Comment by leeoniya** [comment]
cc @mlescaudron via https://github.com/purifycss/purifycss/pull/202

**Comment by leeoniya** [comment]
cc @mlescaudron via https://github.com/purifycss/purifycss/pull/202

**Comment by leeoniya** [comment]
cc @lmrwork

**Comment by leeoniya** [comment]
cc @advanced-site-checker (via https://github.com/FullHuman/purgecss/issues/211)

**Comment by leeoniya** [comment]
cc @lucasvazq (via https://github.com/FullHuman/purgecss/issues/212)

**Comment by lucasvazq** [comment]
The youtuber spammer boy but now in github kjj

**Comment by leeoniya** [comment]
cc @XhmikosR, @luwes (via https://github.com/FullHuman/purgecss/issues/356)

if you can manage to get everything into an html string, DropCSS will probably work well for you(s)

**Comment by luwes** [comment]
@leeoniya using this config

```js
    purgecss({
      content: ['./public/**/*.{html,js}'],
      defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
    }),
```

can DropCSS handle that?

**Comment by leeoniya** [comment]
there's a generic `shouldDrop` callback, so yeah, you'd just have to glob/walks the files and build up the whitelist to test against however you need. however, you'd be missing out on a lot of dropcss's benefits by just pulling all strings out of the html files; it really shines when you let it parse the html files so it can actually properly test the selectors against the dom structure.

**Comment by luwes** [comment]
thanks, I might optimize on this later.
