### ISSUE TITLE
detect selectors from js

### ISSUE THREAD

**Issue by mastef** [leeoniya/dropcss#33]
Not sure if this was already mentioned somewhere else - have you thought of adding a css selector scanner for .js files? Similar to https://github.com/FullHuman/purgecss-from-js-experimental

To be able to detect dynamically added classes - e.g. from carousel plugins and such.

**Comment by leeoniya** [comment]
selector extraction from anything but the final HTML will be imperfect. if you'd like to process JS sources, you can always do this ahead of running DropCSS to build a whitelist and test against that whitelist in `shouldDrop()`. if you look at the source of that plugin [1], its whitelist builder relies on `/[A-Za-z0-9_-]+/g`, which means that things like `let a = "b";` in JS will probably prevent removal of `.a` and `#b` even if those selectors dont actually match anything in your html.

a better bet for accommodating JS properly is to create a script that uses Puppeteer [2] to trigger all/most of the different dom structures and accumulate a whitelist [3]. however, this method is not as "hands off" as the imperfect one.

the general rule of thumb for this lib [in terms of extra functionality] is that anything besides html and css processing should be handled externally to create an appropriate whitelist.

[1] https://github.com/FullHuman/purgecss-from-js-experimental/blob/master/index.js
[2] https://github.com/leeoniya/dropcss#javascript-execution
[3] https://github.com/leeoniya/dropcss#accumulating-a-whitelist
