### ISSUE TITLE
attributes with :

### ISSUE THREAD

**Issue by zavr-1** [leeoniya/dropcss#39]
Hey, attributes can have `:` in attributes, e.g., **svgs** such as `<image xlink:href="example"/>`, the regex needs to be updated.

**Comment by leeoniya** [comment]
try it out. i couldn't run the tests cause suddenly mocha is barfing at me with `MODULE_NOT_FOUND`, even with a cleared cache and an empty test dir 😕

**Comment by zavr-1** [comment]
yeah it worked fine ty

**Comment by tornqvist** [comment]
Is there any chance of a new release with this fix in it?

**Comment by leeoniya** [comment]
i'll cut one today

**Comment by leeoniya** [comment]
1.0.16 is up
