### ISSUE TITLE
Nextjs integration example

### ISSUE THREAD

**Issue by wiesson** [leeoniya/dropcss#45]
How could I integrate dropcss in the nextjs build flow/process?

**Comment by leeoniya** [comment]
i don't use nextjs, so i won't be much help here. dropcss's API is extremely straightforward, so i imagine someone with experience writing plugins for nextjs, postcss, webpack or other bundlers would be more qualified to answer this. you may want to see if the maintainers of https://github.com/lucleray/next-purgecss would be willing to give you some pointers.

you might be interested in reading some prior discussions about integration with other tools:

PostCSS: https://github.com/leeoniya/dropcss/issues/44
Gulp: https://github.com/leeoniya/dropcss/issues/42
Webpack: https://github.com/leeoniya/dropcss/issues/10

**Comment by wiesson** [comment]
Ok, let me have a look, maybe I can submit a PR!

**Comment by leeoniya** [comment]
sounds good :)

**Comment by leeoniya** [comment]
gonna close this for now. if you get around to making a PR, we'll keep talking there.
