### ISSUE TITLE
didRetain() instead of result.sels

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/dropcss#46]
i never quite liked the naming of `result.sels` or that it gets accumulated regardless of whether the user asked for it or not. it also doesnt feel right that whitelist accumulation uses this return style but whitelist testing uses the shouldDrop() callback style. didRetain() which fires for every undropped selector feels more consistent.

this would be a breaking change but to a non-primary API, so i dont think a 2.0 is warranted; hopefully no-one's life depends on dropcss :scream:

**Comment by eemeli** [comment]
I noticed this change while refactoring some code. Dropping `sels` would for us cause things to break stuff. This API is also documented in the README's example code.

I'd recommend you either bump the version to 2.0, or add the new API in parallel with the old.

**Comment by leeoniya** [comment]
yes, i'll likely bump it to 2.0.
