### ISSUE TITLE
Using DropCSS with a Ghost blog

### ISSUE THREAD

**Issue by nsursock** [leeoniya/dropcss#47]
Hello,

I'm working alone on my music blog (https://soundsirius.digitalpress.blog) and I don't have much time every day. I want to use your software to make my website faster. But here's what I need:
- install: be able to use a script tag with a cdn to install it,
- code: generic code I can copy/paste easily to benefit from the basic functionalities.

I installed Tailwind CSS which is very nice but I'm not using everything. I want to get rid of the bad css and css complexity and make my website load under 1 second.

PS: I also want to use CleanCSS before.

**Comment by leeoniya** [comment]
both DropCSS and CleanCSS are build tools which you have to use to first to optimize your css and then put the result on your site. what you're asking is where to buy a hammer which can build you a house

the closest thing to what you're asking for is something like this where you can paste your css for it to be optimized.

https://css.github.io/csso/csso.html
https://jakubpawlowicz.github.io/clean-css/

dropcss's demo is similar to this (paste your html and css, and it will give you the final css):

https://codepen.io/leeoniya/pen/LvbRyq

the demo currently does not perform the additional steps mentioned necessary for Tailwind processing: https://github.com/leeoniya/dropcss#special--escaped-sequences.

i am not sure you will be able to take advantage of dropcss without writing a bit of code. it is not meant to be a hands-off solution and i do not intend for it to be that.
