### ISSUE TITLE
Whitespace inside a closing html tag breaks the parser

### ISSUE THREAD

**Issue by amakhrov** [leeoniya/dropcss#52]
- `<div></div>` parses well
- `<div    ></div>` is good also
- `<div></div   >` fails: `Error: html parser stopped here: "</div >`

All 3 cases are equally correct according to the spec (https://www.w3.org/TR/REC-xml/#sec-starttags)

I wish it was a synthetic case - but that's what Prettier outputs in some cases, so it would be totally cumbersome trying to override

**Comment by leeoniya** [comment]
> I wish it was a synthetic case - but that's what Prettier outputs in some cases

hmm, nothing pretty about that 🤯 

there's likely gonna be a ton of technically-valid-but-breaks-dropcss cases so trying to accommodate what various tools spit out will be an endless game of whack-a-mole.

why not just strip out the whitespace using a regex replace before passing it to dropcss? that's generally my advice in such cases. e.g. https://github.com/leeoniya/dropcss#special--escaped-sequences

**Comment by amakhrov** [comment]
hmmm. unlike the map/undo with regex examples there, I wouldn't be able to undo whitespace stripping.

probably not a big deal though

**Comment by leeoniya** [comment]
lol, why bring back the horror? :D

**Comment by amakhrov** [comment]
I mean - in case it replaced something wrong. Regex is not the best tool for processing html.

Probably better to pre-process it with some html minifier, before calling dropcss

**Comment by leeoniya** [comment]
> Probably better to pre-process it with some html minifier, before calling dropcss}

i was gonna suggest this, but that's a big perf hit.

> Regex is not the best tool for processing html.

no argument there, but i think `</\w+\s+>` is gonna be extremely uncommon to match accidentally. i'd take take that risk 100% of the time vs ingesting another depndency and taking a big perf hit, but that's just me.

**Comment by amakhrov** [comment]
Thank you very much for the quick response!
