### ISSUE TITLE
`NASTIES` regex incorrectly matches custom elements

### ISSUE THREAD

**Issue by amakhrov** [leeoniya/dropcss#53]
Our html includes `<link-formatter>....</link-formatter>`
DropCSS incorrrectly matches it with NASTIES ( this part: `<link[^>]*>`), and drops the opening tag. The resulting HTML becomes incorrect (unbalanced closing tag).

This probably also applies to the `<meta` part of the regex

**Comment by leeoniya** [comment]
does `<link\s+[^>]*>` work better?

**Comment by amakhrov** [comment]
Yep, makes sense
