### ISSUE TITLE
Class names containing html/body/head do not get dropped

### ISSUE THREAD

**Issue by DareFail** [leeoniya/dropcss#58]
Any class name with specific tags in their names will not be dropped even if the html does not contain them.
I explained this second issue poorly in https://github.com/leeoniya/dropcss/issues/57

```
.anyClassNameWithhtml{
  font-weight:400;
}
.anyClassNameWithbody{
  font-weight:400;
}
.anyClassNameWithhead{
  font-weight:400;
}

```

```
<html>
  <div class="nothing"></div>
</html>
```

Thanks for everything!

**Comment by leeoniya** [comment]
i cannot reproduce this: https://jsfiddle.net/m4oqvLgz/

please make a runnable demo.

**Comment by DareFail** [comment]
Apologies - all on my end. Forgot I was trying to whitelist "html, head, body, tbody" as they are implicit
